spring:
  #配置数据源信息
  datasource:
    #    配置数据源信息
    type: com.zaxxer.hikari.HikariDataSource
    #    配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wzj?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置mybatis-plus的全局变量配置
  global-config:
    db-config:
#      设置实体表统一的前缀
      table-prefix: t_
      #      配置mybatis-plus主键策略
      id-type: auto
#      配置类型别民对应的包
  type-aliases-package: com.wzj.mybatis_puls.pojo
  type-enums-package: com.wzj.mybatis_puls.enums
#扫描通过枚举包